@startuml Client Credentials Flow

title Client Credentials Flow
footer RFC 6749 - The OAuth 2.0 Authorization Framework. Section 4.4, Figure 6.

actor "Resource Owner" order 1
participant "Authorization Server" order 2

"Resource Owner" -> "Authorization Server" : Client Authentication
"Authorization Server" --> "Resource Owner" : Access Token

@enduml
