@startuml Resource Owner Password Credentials Flow

title Resource Owner Password Credentials Flow
footer RFC 6749 - The OAuth 2.0 Authorization Framework. Section 4.3, Figure 5.

actor "Resource Owner" order 1
participant "Client" order 2
participant "Authorization Server" order 4

"Resource Owner" -> "Client" : Resource Owner\nPassword Credentials
"Client" -> "Authorization Server" : Resource Owner\nPassword Credentials
"Authorization Server" --> "Client" : Access Token

@enduml
